[package]
name = "spectrum"
version = "1.0.0"
authors = ["Spectrum"]
edition = "2021"
description = "Common spectrum types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cw20 = { version = "0.13.2" }
cosmwasm-std = { version = "1.0.0" }
schemars = "0.8.1"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
uint = "0.9.1"
cw-storage-plus = { version = "0.13.2" }
astroport = { path = "../astroport", default-features = false }

[dev-dependencies]
cosmwasm-schema = "1.0.0"
